# Generated by Django 2.2.5 on 2019-12-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191210_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='currentState',
            field=models.CharField(default='Pending', max_length=15),
        ),
    ]
