# Generated by Django 2.2.5 on 2019-12-13 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0021_exchangeproductpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0012_petition_currentstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangePetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentState', models.CharField(default='Pending', max_length=15)),
                ('hisProduct', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='EhisProduct', to='parapop.ProductPost')),
                ('product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Eproduct', to='parapop.ProductPost')),
                ('reciever', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Ereciever', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Esender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
