# Generated by Django 2.2.5 on 2019-12-13 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_exchangepetition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangepetition',
            name='hisProduct',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='EhisProduct', to='parapop.ExchangeProductPost'),
        ),
        migrations.AlterField(
            model_name='exchangepetition',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Eproduct', to='parapop.ExchangeProductPost'),
        ),
    ]
