# Generated by Django 2.2.5 on 2019-10-14 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0006_auto_20191014_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpost',
            name='author',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
