# Generated by Django 2.2.5 on 2019-10-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0009_auto_20191014_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpost',
            name='productPic',
            field=models.ImageField(default='defaultProduct.jpg', upload_to='media/product_pics'),
        ),
    ]
