# Generated by Django 2.2.5 on 2019-10-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0010_auto_20191015_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpost',
            name='productPic',
            field=models.ImageField(default='defaultProduct.jpg', upload_to='product_pics'),
        ),
    ]
