# Generated by Django 2.2.5 on 2019-10-15 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0012_auto_20191015_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpost',
            name='productPic',
            field=models.ImageField(default='defaultProduct.jpg', upload_to='product_pics'),
        ),
    ]
