# Generated by Django 2.2.5 on 2019-10-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0013_auto_20191015_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpost',
            name='productPic',
            field=models.FileField(upload_to='product_pics'),
        ),
    ]
