# Generated by Django 2.2.5 on 2019-10-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0015_auto_20191016_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='productpost',
            name='tag',
            field=models.ManyToManyField(to='parapop.Tag'),
        ),
    ]
