# Generated by Django 2.2.5 on 2019-12-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0016_auto_20191022_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
            ],
        ),
    ]
