# Generated by Django 2.2.5 on 2019-12-09 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0017_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
