
# Generated by Django 2.2.7 on 2019-12-18 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0017_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
