# Generated by Django 2.2.5 on 2019-12-10 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parapop', '0018_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpost',
            name='purchased_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchased_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
