# Generated by Django 2.2.5 on 2019-12-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0019_productpost_purchased_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpost',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
