# Generated by Django 2.2.5 on 2019-12-13 16:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parapop', '0020_productpost_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeProductPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('productPic', models.FileField(upload_to='product_pics/')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('favUsers', models.ManyToManyField(blank=True, related_name='EfavUsers', to=settings.AUTH_USER_MODEL)),
                ('purchased_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Epurchased_by', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(to='parapop.Tag')),
            ],
        ),
    ]
