# Generated by Django 2.2.7 on 2019-12-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0020_auto_20191218_2034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpost',
            name='pub_date',
        ),
    ]
