# Generated by Django 2.2.7 on 2019-12-18 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0021_remove_productpost_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpost',
            name='pub_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
