# Generated by Django 2.2.7 on 2019-12-18 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0022_productpost_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productpost',
            name='pub_date',
        ),
    ]
