# Generated by Django 3.0 on 2019-12-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parapop', '0024_productpost_pub_date'),
        ('parapop', '0021_exchangeproductpost'),
    ]

    operations = [
    ]
